language: python
python:
  - '2.7'

sudo: false

install:
  # Python test requirements
  - pip install -r src/vendor/python-requirements-dev.txt

script: 'make tests-travis'

addons:
  apt:
    sources:
    - chris-lea/node.js
    packages:
    - nodejs
