language: python
python:
  - '2.7'

sudo: false

install:
  # Python test requirements
  - pip install -r src/vendor/python-requirements-dev.txt
  # JavaScript test requirements
  - add-apt-repository -y ppa:chris-lea/node.js
  - apt-get -y update
  - apt-get -y install nodejs
  - npm install -g grunt-cli
  - npm install

script: 'make tests-travis'
