language: python
python:
  - '2.7'

install:
  # Python test requirements
  - pip install -r src/vendor/python-requirements-dev.txt
  # JavaScript test requirements
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm install -g grunt-cli
  - sudo npm install

script: 'make tests-travis'
